//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.SqlClient;

namespace CombinedGraph
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.EntityClient;
    using System.Data.Entity.Infrastructure;

    public partial class airscanEntities : DbContext, IDisposable
    {
        public static string conn
        {
            get
            {
                 DbServer server = new DbServer();
                return DbServer.connString;
            }
        }
        public airscanEntities()
            : base(conn)
        {
        }

        //public airscanEntities(EntityConnection conn)
        //{
        //    this.conn = conn;
        //}

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<measuring> measurings { get; set; }

        public void Dispose()
        {
            
        }

        public static string ConnectionState { get; set; }

    }
}
